version: "3.8"

services:
  stub:
    build: .
    environment:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_TOKEN:
      TWITTER_TOKEN_SECRET:
    networks:
      - recotw
    volumes:
      - ./data:/data

networks:
  recotw:
    name: recotw
